### ISSUE TITLE
Hackathon Minutes

### ISSUE THREAD

**Issue by zth96** [coruubc/diverse_price_prediction#1]
**Discussion Points with our Partner:**

1. How was data wrangled/what do the files mean? Can we have the data wrangling file? (e.g. PPP)
2. What is Tonnes and GlobalTonnes column refer to? Where to find the tonnes/ log prices variables data? 
3. Explanation on why not including other columns in the current model?
4. Discuss PPP vs Country when its already adjusted.
5. Should we predict by year, country, by species, by port? (If our prediction goal align with the previous model)?
6. What is the difference between SSP1, 3, 5, etc.? 
7. Do we need separate model to different scenarios? 
8. The zeros in the prices, does that mean no trading of that species at the certain port or is the zero for imputation? 
9. Preference on the end product, a model or a pipeline? 
10. Does it has to be log-prices for the predictions? 
11.

**Comment by gtmx23** [comment]
Thanks for taking notes! The responses to some of these questions are as follows (thanks also for helping to take notes for this part!):

- We were wondering if it is possible for us to have access to the data wrangling file used to produce the DATA dataframe used in the model? This is as we were unable to match some of the columns used (For example, logPrice, Tonnes and GlobalTonnes).
  - For the data, I will check my database, and we will discuss it tomorrow. 
- We noticed a lot of 0s in the data for Price_PPP and Production, and were wondering what they mean - does this mean the data was missing?
  - For the 0, not necessary NA but no production (tonnes) , hence no price value. 
- We noticed that the SSP file had SSP1/3/5, but the values were often identical (up till 2015). We were wondering if we want to use all the values for prediction, and more generally what they mean?
  - The SSPs values up till the 2015 are historical values. They should be identical. . 
- We were wondering if the end product should be a data pipeline or just scripts of the working models.
  - I think both. Yes, we will discuss more tomorrow.

- Price prediction should be by EEZ by species by year
- May merge countries together for same species for prediction
- Why was logPrice used? +  Clarification on why PPP was used
  - Sum by EEZ
  - Tones/ GLobal Tones -> total
  - Price are in USD, already accounted for inflation
  - Avoid price disparity with logPrice
- 0s in Data
  - Years catching nothing, there is no production. 
  - Remove years of zeros
  - There is no missing data
  - If it is NA, the data is not available. 
- Ways to aggregate price of species? 
  - May aggregate by EEZ or by country (country are sum of 2 or 3 EEZ) 
- Why were other columns (species, country) not included in the model?
  - Considering Demand and Supply
- Expectations for progress for next meeting (Ask Muhammed)
  - Play with current model and understand how it works
- How was model evaluated 
  - Current Model: 70/30 split and test on current data. 
  - Future Model: Any metrics we can decide and justify

- Production Data: Will be shared. (Currently only up to 2015)
- 
- Include categorical features? Up to us. May do it by species group; 
- Data Product Expectations
  - Model is the key
  - A paper report on how to use the model
  - May have a pipeline, but doesnt sound like there will be new data

**Comment by zth96** [comment]
Hackathon Day3 Minute
 -To be resolved
Historical data for population & consumption seems off, need to double check with partner on data accuracy
There are a lot of missing data for Hong Kong and Taiwan (no price or no production), can be a systematic missing, discussion if we should drop this two locations
One species price went sky high and sudden drop, double check the data accuracy of explanation on the price fluctuation.
-To do
Continue on data cleaning and exploration
Finish the group proposal slides
Get read for rehearsal presentation tomorrow
