### ISSUE TITLE
Week 2 Standup Meetings

### ISSUE THREAD

**Issue by gtmx23** [coruubc/diverse_price_prediction#16]
# 20240507 Standup
### Updates From Yesterday
**Sho**
- Posted a Rmd on GH, plan to update this document as he explores the data further
- EDA/graphs of data 
  - Population issue: Some countries had different EEZs with different population - counted as duplicates in population aggregation, causing the sharp rise
  - Ended up dropping Taiwan and HK, population looked smooth after that
  - This solved ~60% of issues with PPP/production where there were 256 rows with missing data
  - Remaining 40% discrepancy: Where there is production but no price - probably not a big issue, makes sense
- Data cleaning: Taking out HK and Taiwan helped a lot
  - Used sam's cleaning ipynb
  - Kept 0 entries for price - makes sense that some places might have production but no price if no one wants to buy
- 184000 observations left after cleaning, sufficient for NN training

**Sam**
- Explored code
  - Generally: Data was wrangled and put into the inputs folder, code reads data in input folder
- Cedar: data loading and wrangling
- Socioeconomic data: more complete wrangling, with outputs saved in scenario folder
-  We probably don't need to care too much about code since it already produced the output we are looking at
  - We can do further wrangling on our own later if needed
  - For now, we can keep features, clean data further and fit neural network, see if it works
- Features used to train NN can be confirmed tomorrow (point 3 of md file)
- Linear regression was used to project future production using GDP and country code (point 4) which are already features included in the model
  - Question: Why are we using the same variables twice in our model? 
- To clarify `X.kg` (point 5)
- Figure out which files in input folder correspond to ground truth, ask about flexibility in feature choice

**Gretel**
- Did administrative set up and report (Executive summary and introduction - 718 words)
- Full proposal report has 1900 words at present excluding references

**Sophia**
- 1 graph for PPP and Production would be good (@sho-i98 will upload in his own branch)
- Was trying to cut today

### To Dos
**Report**
- [ ] Can all look at report together and see where we can cut words/duplicated sections
  - Main task of the morning 

**Data**

- [ ] Work on further understanding the data in the afternoon
  - @sho-i98 will look at what @fohy24 did
  - Link data in the inputs folder to the model feature they are related to

**Meeting Prep**
- [ ] Everyone to familiarise ourselves with code William sent
  - Using data team's deliverables  
- [x] #17
  - Google doc to be sent to partner
  - GH Issue will be made too

**Comment by gtmx23** [comment]
To clean up and organise later

**Comment by gtmx23** [comment]
Heyo @sho-i98 you mentioned everyone familiarising ourselves with the partner's code and data - just to clarify, will looking at the summary md files from the data team be sufficient or do you suggest something else? This is as I will probably be focusing on refining the report for today and want to budget for the time I need to explore the data tomorrow morning. Thanks!

**Comment by sho-i98** [comment]
hey @gtmx23, thank you for working on refining the report. Please take your time on reports today, summary from Sam and I should be sufficient. Please do let us know in the chat if there is anything we can do to help with the refining process.

**Comment by gtmx23** [comment]
# 20240508 Standup
### Meeting discussion
- Discussed briefly what we should do during the meeting
- @sho-i98 will lead, cover proposal points
### Updates from yesterday
- Did report

### Clarifications
- How close are we to cleaned data?
  - If we are treating data as is, looking quite good
  - In data validation phase
  - Training dataset is currently relatively clean, need to clarify some things for Tonnes though
  - Drop duplicates for price and tonnes - but there are some subunits with the same EEZ and species but with different prices, should we just take the average?
  - Need to clarify some stuff 

### To dos
- Logistics day given the EDI today
- Clarify with partners - why for Tonnes projection we only have SSP1xx and 5xx
- Cleaned data to be uploaded on GH repo by end of the week after clarification with partners
  - Depending on complexity of answers received during clarification
- Can take Friday
