### ISSUE TITLE
20240508 Partner Meeting Agenda

### ISSUE THREAD

**Issue by sho-i98** [coruubc/diverse_price_prediction#18]
**Partner Meeting Agenda**
**Date:** May 08, 2024
**Time:** 11:00 am
**Location:** https://ubc.zoom.us/j/62298746319?pwd=Y3FOR3B2bElzaU5BVERkNUJsajlSQT09

###  Agenda Items:
1. Update from the last week (~10 mins)

- SSP Population data misalignment
- Current model/data schema - issues identified

2. Proposal (~15 mins)

- Data Handling techniques, such as merging via Species and SubUnit
- Universal model that makes predictions for specific EEZ/Species combinations (Borrowing strength)
- Brief explanation of timeline

3. Questions from the team (~30 mins)

- Clarify scope of the project and where it fits in the overall DIVERSE framework
- Clarify the team’s understanding of William’s code  (Potentially take away projected Seafood Consumption figures from the model) [link](https://github.com/coruubc/diverse_price_prediction/blob/model-findings/partners_model_findings/findings-20240506-sam.md)
- Data validation (Production with no price) and the sources of data [link](https://github.com/coruubc/diverse_price_prediction/blob/model-findings/partners_model_findings/findings-20240506-sho.md)
- Variability in price and production- is it normal in seafood prices or should that be taken away?
- Some EEZs share the same prices and tonnes, but some don’t
- SSP1 and SSP5 only available for projected “Tonnes” dataset
- No fishery data

4. Action items/expectations for next week (~5 mins)

**Comment by gtmx23** [comment]
# Minutes
## Updates
**SSP Population data misalignment**


**Current model/data schema - issues identified**

## Questions from the team
**Clarify scope of the project and where it fits in the overall DIVERSE framework**


**Clarify the team’s understanding of William’s code (Potentially take away projected Seafood Consumption figures from the model) [link](https://github.com/coruubc/diverse_price_prediction/blob/model-findings/partners_model_findings/findings-20240506-sam.md)**


**Data validation (Production with no price) and the sources of data [link](https://github.com/coruubc/diverse_price_prediction/blob/model-findings/partners_model_findings/findings-20240506-sho.md)**


**Variability in price and production- is it normal in seafood prices or should that be taken away?**

## Action items/expectations for next week

- [ ]

**Comment by gtmx23** [comment]
Hey @sho-i98, thank you for moderating the meeting :) I was wondering if I/you could edit your issue to add in the action items we discussed? This is to facilitate the creation of action item issues linked to this issue, for addition to our project board. I think it would be nice to be easily linked back here when clicking on the action item issue! Let me know your thoughts :) and see you soon!
