### ISSUE TITLE
Week 3 Standup Meeting Minutes

### ISSUE THREAD

**Issue by zth96** [coruubc/diverse_price_prediction#31]
Monday May 13th. 
1. Merge the pull requests for data cleaning from Sam and merge EDA pull request from Sophia. @team
2. Sam finish the data cleaning . @fohy24 
3. Summarize questions to discuss with Alexi on weekly meeting. @team
- How to apply ARIMA under this condition?
- How to do detrending?
- 
5. Preprocessing with different methodology -TBD
6. Initiate on ARIMA (after discussion with mentor) -TBD
7. Multiple Linear Regression   - TBD
8. Dummy Model - TBD

**Comment by sho-i98** [comment]
### 20240514 Standup Meeting

## Updates:
Sam:
Linear Regression for RMSE: 32 - 33
Coefficient Analysis: Species are the leading factor, GDP/Pop/SeafoodConsumption affects price positively, Year has negative coefficients.
Removing Consumption --> Valid score is very similar.
Removing Year --> No monotonic increase/decrease

Sophia:
Temporal detrending: No detrending methods work.
EDA: Production and Consumption have a steady increases. Some correlation made intuitive sense but some contradicts.

Gretel&Sho:
Train RMSE at 38, and Valid RMSE at 15, not ideal.
The log data has still huge variation --> scale the logged features?

## Agenda for afternoon:
Gretel&Sho: Log data then scaling, use 15 years (1995-2010) to train and first 5 years (1990-1994)  to valid
Sam: LMEM in Python
Sophia: Finish EDA, Make the plots
