### ISSUE TITLE
20240513 Meeting with Alexi Minutes

### ISSUE THREAD

**Issue by sho-i98** [coruubc/diverse_price_prediction#35]
### Milestone for this week
- Clean Data
- Apply to Dummy Model (DummyRegressor for Mean)
- Regression
- ARIMA model
- Preprocessing

### Questions to ask Alexi
- How to apply classical time series models on our data
  - How is the categorical features fit into ARIMA model? -->Dynamic regression models (Forecasting: Principles and Practice)
  - --> Perhaps abandon ARIMA
  - Mixed Effect Models, group by country (562 Lecture 4 11 company examples. i is year, and j is the country)--> All the species will have the same prediction within each country
  - --> Random effect in each country
  - Average --> OLS --> ME by Country --> ME by 
- How does the detrending work in our model
  - Change features to % changes over time
- Data Splitting strategy (Shuffling vs Non-shuffling)
  - Window split
- Python package LICENSE
  - Check the GitHub repo for the package we are using and go to License. Assess if we can use that packge for our purpose

### Tips
- Document all the steps along the way
- Unit test (Data product rubric)
- Alexi to send Final Documnet rubric

### To Do
- Structure the report as starnadardized format
- Repository structure
  - Model folder to explore different models
- Data
  - Add logarithm of GDP/Population/Seafood consumption (Sophia)
  - Splitting might come up issues because EEZ/Species combination very few
  - --> Only train on 1990 to 2005, and instead of CV, treat 2005 and 2010 as our validation set
- EDA
  - More data validation, and specific EEZ/Species combination
- Model
  - Multiple Linear Regression (Sam)
  - Mixed Effect Model (EEZ, Species) (Sho, Gretel)
 
  
### Preparation for partner meeting
- Emphais on historical data is used to training and projection to make prediction 
- Prepare a jupyter notebook during a meeting
- Start simple then build up step by step
- If % change in preprocessing, how would that feed into overall DIVERSE model?

### Action Items
- Team decided to group by species/EEZ instead of country since it is more in line with partner objectives
- [x] #37
- [ ] #38
- [x] #39

### Official Deadlines
- [ ] 14 May EOD: Send agenda

**Comment by zth96** [comment]
Thanks Sho for taking the notes!
Just to add on to relevant issues. I have the below issues (two outstanding one closed regarding EDA and cleaning) 

New Detrending methods and temporal/ geospatial EDA #36
More Visuals for Data Exploration and Documentation #33
Data Cleaning with Detrending and Comsumption #32

Thanks!
