### ISSUE TITLE
Implement LSTM

### ISSUE THREAD

**Issue by gtmx23** [coruubc/diverse_price_prediction#56]
- Implement LSTM (pytorch for ability to explain what we are doing)
- Tune RNN
- Documentation

**Comment by zth96** [comment]
Couldn't run a in depth LSTM through cross validation. Tried a simpler LSTM with one LSTM layer and 50 hidden units. 
<img width="896" alt="image" src="https://github.com/coruubc/diverse_price_prediction/assets/143483779/f04c6165-6e76-4ae4-a402-aaf7c5158e30">

Prediction result is like this with an Average RMSE of 8.34 and Average MAE of 4.82
