### ISSUE TITLE
Meeting Minute with Mentor 20240526

### ISSUE THREAD

**Issue by zth96** [coruubc/diverse_price_prediction#59]
Meeting Minute from 20240526

- [ ]  Explain expanding window approach, visualize how we do the expanding window.
- [ ]  For hyperparameter tunning, explain what is it, why we are doing this and what's the result.
- [ ]  For the current best performing model (GBTM); brief explanation on the model type, how the model work, and address the model interpretability.
- [ ]  For neural network models (especially RNN, and LSTM), explain the model and show the performance, also address its flaw.
- [ ]  For the best performing one (or best two) model(s), explain how the prediction works across three different EEZs. Evaluate the prediction performance
- [ ]  Plan for coming week: Pick a winning model, documentation on all works done, explain all modeling approaches.
- [ ]  To confirm with partner how they plan to use the model in the future.
- [ ]  Regarding the stretch goals, focus on doing the pipeline first and consider simple dashboard if time allows.
- [ ] Feel free to add anything in if there is a missing point.

**Comment by gtmx23** [comment]
Thanks Sophia!

**Comment by gtmx23** [comment]
# Proposed Meeting Agenda
## Updates
- Implementation of expanding window approach 
- Update on performance of models (NN, XGBoost, RNN, LSTM) and compare this to previous models (LME and LR)
- Any challenges we might be facing

## Questions
- NN performance does not seem as good as expected
- Next models to try: Transformers? Something else?
- Should we move forward with our stretch goals or focus on refining current models/something else?

## Action Items

**Comment by gtmx23** [comment]
- Explain expanding window 
- Highlight why we chose to use it

**Comment by zth96** [comment]
### Meeting Minute from 20240526

- [ ] Explain expanding window approach, visualize how we do the expanding window. 
- [ ] For hyperparameter tunning, explain what is it, why we are doing this and what's the result. 
- [ ] For the current best performing model (GBTM); brief explanation on the model type, how the model work, and address the model interpretability. 
- [ ] For neural network models (especially RNN, and LSTM), explain the model and show the performance, also address its flaw. 
- [ ] For the best performing one (or best two) model(s), explain how the prediction works across three different EEZs. Evaluate the prediction performance 
- [ ] Plan for coming week: Pick a winning model, documentation on all works done, explain all modeling appraches. 
- [ ] To confirm with partner how they plan to use the model in the future. 
- [ ] Regarding the stretch goals, focus on doing the pipeline first and consider simple dashboard if time allows. 

Feel free to add anything in if there is a missing ppoint.

**Comment by gtmx23** [comment]
Thanks Sophia!
