### ISSUE TITLE
20240506 Meeting with Alexi Minutes

### ISSUE THREAD

**Issue by gtmx23** [coruubc/diverse_price_prediction#6]
### Logistics
- Draft proposal report due **Tuesday 7 May 6 pm** 
  - 1200 words
  - First draft not graded
  - Include SSP stuff from introduction
  - Remember to cite, include references at the end
  - Submit as a **PDF on internal channel** tomorrow
  - Final submission: **Rmd file**
  - Partner won't see the draft: **don't commit draft to repo, work on Google Doc** and paste into an Rmd later
- Feedback will be sent by end of 8 May (Wed) 
- 10 May 6 pm (Fri): Submit **link to final proposal (HTML/PDF) on partner's repo to Canvas for grading**, send link to proposal of repo by that time on the **shared channel**
  -  Make folder for reports on repo and put final proposal there

 
 **Presentation**
- Alexi will send internal comments on the presentation to us on the internal channel
  - Main issue: Still need to define in a clear way the global objective of the project - what is the final goal (may get a clearer ans on Wed), success criteria
    - Eg fish price based on EEZ incorporating information from macroeconomic (I didn't catch it sorry! @zth96 got it I think, do you mind pasting it?)

### Data
- Problem: HK and Macau have quite a lot of rows with catch but no price, there may be a systematic error so we are not sure how to handle it 
  - To add to agenda on Wednesday and discuss with partner

### Action Items
- [x] #7
- [x] #8
- [x] #9
- [x] #10
- [x] #11
- [x]  Split team in 2: 2 work on report and 2 to work on data
- [x] #12
    - Objective: Explore the code and data from the new folder, summarise and organise
    - Deliverables: Put interesting findings in a document for @gtmx23 and @zth96 to follow + include in proposal if needed
 - [x] #13
- [x] Paste scripts on Google docs (@zth96 @sho-i98 @fohy24)
  - Scripts were sent on Slack
- [x] #14
  - Format: GH Issue, first post of issue will be agenda, follow up post will be action items/what we agreed to
  - **Main issues to bring up in meeting**:
    - Proposal (10 min)
      - Highlight important parts of proposal - proposed data handling/modelling approach
        - Borrowing strength: Analogous to EEZ - hierarchical modelling
    - Issues/Problems we faced (15 min) 
      - HK/Macau data (Include plots/figures/numbers to show the issue - show and tell exactly what the problem is and back up issue)
    - Clarify William's code/project scope (30 min)
      - Where in the DIVERSE framework does our project fit in
      - How to put William and Muhammed's parts together
    - What we will do in the future (~5 min?)

### Internal Deadlines
Data Team
- [x] Summary of what is happening in data/code **EOD (midnight) today**
  - @sho-i98 population and HK Taiwan stuff
  - @fohy24 to look at new code and data first
  - How our part comes in, how the 2 parts of the project come together
Report Team
- [x] @zth96 will do draft of her part before 9 am meeting
- [x] @gtmx23 will also do draft of her part before 9 am meeting
- [x] To submit draft by **noon** to Alexi (PDF)
Admin
- [x] #15
- [x] @gtmx23 to clean up minutes (DONE)

### Official Deadlines
- [x] 7 May EOD: Send agenda
- [x] 8 May 6 pm (verify later) Draft proposal
- [x]  10 May 6 pm Proposal

**Comment by gtmx23** [comment]
Clean up later

**Comment by zth96** [comment]
We’ll use this Google Doc to draft our proposal report version 1
https://docs.google.com/document/d/1ikKQfeHOduTa2DwYA8MHhO0VNIYPxGonibGvuzfvBeY/edit

**Comment by zth96** [comment]
Thanks Gretel for taking the meeting minutes. Sorry I didn't take down notes for this section either. ( fish price based on EEZ incorporating information from macroeconomic)

Just a quick check, was it HK and Taiwan or HK and Macau having the missing data problem? 

Everything else looks great!
