### ISSUE TITLE
Draft of Dashboard

### ISSUE THREAD

**Issue by gtmx23** [coruubc/diverse_price_prediction#70]
- @sho-i98 to generate predictions as csv using winning model from @fohy24 
- @zth96 to explore potential platforms, maybe get started with first draft of dashboard on Monday
  - Since we are not using Tableau maybe it is ambitious to have 1 person do the first draft? What do you think haha
- To use Streamlit/Dash since we do not have Tableau access

**Comment by zth96** [comment]
Hi team, please see attached a recording of the dashboard progress so far. 

The three major components price line chart, feature table, and feature line charts are done with all the filters and restrictions applied. 

The theme color is set as blueish for the ocean theme. 

What is left to be done is formatting the content and beautify that I'll left to do tomorrow. 

Let me know if any comments or suggestions

https://github.com/coruubc/diverse_price_prediction/assets/143483779/b3818d30-8176-4461-97cf-4ec221ea1a45

**Comment by zth96** [comment]
Prepared the horizontal version of the dashboard, made improvements on figure formate, font style, decimal points, etc. 
Verified the call backs and filter/ slicers functions. All performing as expected. 
May consider adding in logos for the dashboard. 

https://github.com/coruubc/diverse_price_prediction/assets/143483779/380ed3e3-e831-4ff3-8867-e155f9eb402c
